### ISSUE TITLE
Script for preprocessing pix3d

### ISSUE THREAD

**Issue by chicleee** [yinyunie/Total3DUnderstanding#1]
Hi, thanks for the great repository.

I download your preprocessed Pix3D ground-truth data, but I don't know how do you sample 3D points on meshes and how to process Pix3D datasets to '.pkl' files .

Can you please share your methods or scripts for preprocessing pix3d dataset?

thanks in advance.

**Comment by yinyunie** [comment]
Hi,

The preprocessing script for pix3d is updated.

We just sampled random points on pix3d meshes as we observed the models are relatively clean with minor inner structures. But we recommend to scan the surface points with virtual cameras if you want a better preprocessing or to use another dataset for training.
