### ISSUE TITLE
build.pyd

### ISSUE THREAD

**Issue by jiafr1802** [yinyunie/Total3DUnderstanding#10]
When running the command "**python main.py configs/total3d.yaml --mode demo --demo_path demo/inputs/1**" on Win10 platform, I got an Import Error. Judging by **build.so** file under the directory **/Total3DUnderstanding/external/pyTorchChamferDistance/build**, you might use unix system. But for windows, I guess I need the corresponding build.**pyd** file for running. Could you please offer this .pyd file?

**Comment by yinyunie** [comment]
Hi,

I did not find any build.pyd files. For the chamfer distance library, please refer to https://github.com/chrdiller/pyTorchChamferDistance

**Comment by jiafr1802** [comment]
Before running the command **"python main.py configs/total3d.yaml --mode demo --demo_path demo/inputs/1"**, the build.ninja file in **/Total3DUnderstanding/external/pyTorchChamferDistance/build** is like the figure below:
![build so](https://user-images.githubusercontent.com/47714545/91678861-44704500-eb79-11ea-8ad9-b8f7f75cb807.jpg)

However, after running the command (on win10), the build.ninja turned to the figure below:
![pyd](https://user-images.githubusercontent.com/47714545/91678939-7a152e00-eb79-11ea-83bc-f311ddc372be.png)

In the last 2 lines, you can find the mention on **build.pyd**. I guess it means the pyd file is needed in windows platform just as the build.so file in linux platform.  I think the **build.pyd** should be compiled from cpp source codes and it is necessary for building python module. 
Since there is no build.pyd file, could you please offer one?
