### ISSUE TITLE
3D detection is not working well with custom input 

### ISSUE THREAD

**Issue by WenM1222** [yinyunie/Total3DUnderstanding#24]
Hi, I tested with a image from 3D-Future dataset, and the 3D bounding box looks not well predicted. Is this normal? 
This is the test data. 
[custom.zip](https://github.com/yinyunie/Total3DUnderstanding/files/5616858/custom.zip)

And test result. 

![custom_image_detect_scene_res](https://user-images.githubusercontent.com/22854214/100629563-c6d0f680-336c-11eb-810e-a5ee76676581.png)
![custom_image_mesh_scene_res](https://user-images.githubusercontent.com/22854214/100629579-cc2e4100-336c-11eb-9678-bad6989bc438.png)

**Comment by Washeded** [comment]
Hi, I have met the same problem. And I calibrated my camera intrinsic parameters. Do you have any solution for this?

**Comment by WenM1222** [comment]
Sorry, I haven't find solution yet.

**Comment by yinyunie** [comment]
It is perhaps for the reason that our model is only trained on SUN RGB-D. The input distribution (intrinsics, images) is quite different from yours. I also received some suggestions about using our model on in-the-wild images. You can also try it by using the same intrinsics as ours and preprocess the images that appear similar to SUN RGB-D (scale or center crop). But it is only for visual appearance, no guarantees on accuracy.
