### ISSUE TITLE
The visualization

### ISSUE THREAD

**Issue by ysunbp** [yinyunie/Total3DUnderstanding#3]
It seems that the test command can only generate meshes in .obj format and their metadata. Is there an easy way to generate the images(screen shot?) of the resulting 3d scene?

**Comment by yinyunie** [comment]
I updated the utils/visualize.py. You can visualize a 3D scene in the test set of SUN RGB-D by giving a test id as:
python utils/visualize.py --result_path out/total3d/a_folder_named_with_script_time/visualization --sequence_id 274

**Comment by yinyunie** [comment]
I updated the utils/visualize.py. 

After the metadata is generated in testing, you can visualize a 3D scene (only in the test set of SUN RGB-D) by giving the sample id as:
python utils/visualize.py --result_path out/total3d/a_folder_named_with_script_time/visualization --sequence_id 274

You can also save the screenshots by turn on the 'if_save' in the visualize.py file.
