### ISSUE TITLE
vtk headless mode

### ISSUE THREAD

**Issue by nikhilaravi** [yinyunie/Total3DUnderstanding#30]
Is it possible to run the demo code without requiring a display for vtk for visualization?

**Comment by alando46** [comment]
If I understand you correctly, I think you should be able to just comment out the last two lines (or more) from [demo.py](https://github.com/yinyunie/Total3DUnderstanding/blob/master/demo.py#L230-L231). You should be able to ship all of the generated assets (`demo/outputs/{1-5}`) to object storage for later review.

**Comment by yinyunie** [comment]
Hi,

You can use the offscreen rendering with vtk.  check `render_window.SetOffScreenRendering(True)` and ` vtk.vtkWindowToImageFilter()` for rendering, but you should play with the camera viewpoint a bit. A rendering demo.py in our new project is at https://github.com/yinyunie/RfDNet

Best,
Yinyu
