### ISSUE TITLE
The set up of camera coordinate system

### ISSUE THREAD

**Issue by ysunbp** [yinyunie/Total3DUnderstanding#4]
Hi! Can I ask a question in your paper?
In your paper, it stated that: "We set up the world system located at the camera center with its vertical (y-) axis perpendicular to the floor, and its forward (x-) axis toward the camera, such that the camera pose R(;) can be decided by the pitch and roll angles (; )." I do not quite understand how can the y-axis which is perpendicular to the floor be set while the x-axis is set towards the camera. In this case, the x and y-axis are not perpendicular if the camera is not looking at the horizontal direction. Or if the meaning of towards does not imply that the x-axis is parallel to the camera's optic axis, but just an axis that passes through the camera center and perpendicular to the y-axis defined.
I am quite confused about this part. Could you please elaborate a bit? Thanks.

**Comment by yinyunie** [comment]
Hi,
Yes, 'toward' here does not mean 'parallel'. The x-axis of the world coordinates passes through the camera center, perpendicular to the y-axis, and coplanar with the 'forward' axis of the camera and the y-axis (see the figure below).
![1594480504(1)](https://user-images.githubusercontent.com/25686434/87227260-bbffd000-c391-11ea-8450-3dbe341609e1.jpg)
