### ISSUE TITLE
Where to find the supplementary file?

### ISSUE THREAD

**Issue by JunxuanBai** [yinyunie/Total3DUnderstanding#40]
Hi, yinyu,

A very nice work! I am looking for the supplementary file mentioned in the corresponding paper. Where can I get this file?
Thanks!

Junxuan Bai

**Comment by Harvey-Mei** [comment]
HI Bai,
you can find it [here](https://openaccess.thecvf.com/content_CVPR_2020/html/Nie_Total3DUnderstanding_Joint_Layout_Object_Pose_and_Mesh_Reconstruction_for_Indoor_CVPR_2020_paper.html)

**Comment by JunxuanBai** [comment]
Thank you!

**Comment by JunxuanBai** [comment]
Thank you!
