### ISSUE TITLE
The pretrained model's link

### ISSUE THREAD

**Issue by SunWeiLin-Lynne** [yinyunie/Total3DUnderstanding#45]
Hello, the download link for the pretrained model has expired. 
Can you update the download link again? 
Looking forward to your reply!

**Comment by yinyunie** [comment]
Hi, I have updated these links. Please check again.

Best,
Yinyu

**Comment by yinyunie** [comment]
Hi, I just fixed them. Please have a check.

**Comment by qijiahui7** [comment]
Hi @yinyunie , the links seem to have expired again -- could you re-upload?

**Comment by yinyunie** [comment]
@qijiahui7 Hi, I have updated them. Please check again.

**Comment by iordachelivia** [comment]
Hello, the link expired again, could you upload it?

**Comment by yinyunie** [comment]
> Hello, the link expired again, could you upload it?

Hi,
I just updated these links. Could you please check again?

**Comment by iordachelivia** [comment]
It works now, thank you very much!
