### ISSUE TITLE
Errors when processing raw SUNRGBD data

### ISSUE THREAD

**Issue by SeanChenxy** [yinyunie/Total3DUnderstanding#6]
Hi, Thank you for your sharing.
When I use `generate_data.py` to process SUNRGBD data, I get an error, i.e., `json.decoder.JSONDecodeError: Expecting ',' delimiter`. I have carefully checked the JSON file, e.g., `SUNRGBD/kv2/kinect2data/000467_2014-06-09_19-35-24_260595134347_rgbf000188-resize/annotation2Dfinal/index.json`. This JSON file does have an error in JSON format. That is, `{"name":"wall\"}`'in this file should be `{"name":"wall"}`.

So, I wonder whether you suffer from this problem, and how to solve it? Thanks a lot.

Another beg. Could you put the processed data on GoogleDrive so that we can conveniently download them with `gdown` on the server.

**Comment by yinyunie** [comment]
Thank you for reporting this.

Indeed some SUN-RGBD samples have this problem. Just removing the backslash in "wall\" will solve it. I have updated the script to automatically fix this issue. 

Sorry about the source. As OneDrive is a partner of our University, I think we will currently keep the data in OneDrive.

**Comment by SeanChenxy** [comment]
Thank you for your help, but I cannot find errors in some JSON files. For example, `SUNRGBD/kv1/b3dodata/img_0174/annotation2Dfinal/index.json` also suffers from the problem of `JSONDecodeError: Expecting ',' delimiter`. Could you help me process it? Thanks a lot.

**Comment by yinyunie** [comment]
There are few typos in these *.json files. Many of them are irregular. I updated the script for the new case in this json reader
[link](https://github.com/yinyunie/Total3DUnderstanding/blob/master/utils/sunrgbd_utils.py#L185). Updates for any new cases are welcome.

**Comment by SeanChenxy** [comment]
I have processed them. Thanks a lot.
