### ISSUE TITLE
dataset split

### ISSUE THREAD

**Issue by Faye0123** [yinyunie/Total3DUnderstanding#7]
Hi there!
Thanks for the great repo.
I have a problem with the sunrgbd dataset that I didn't find the train/test split after downloading your provided processed dataset.
Could you suggest where I can get it?
Thanks!

**Comment by yinyunie** [comment]
Hi,

You can find the splits in `data/sunrgbd/splits/`

**Comment by Faye0123** [comment]
Great! I should not have missed it.Thanks for the reply!
